apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-secrets
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: monitoring
    repoURL: git@github.com:marklester/moonbase-secrets.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true       # Automatically delete resources no longer in Git
      selfHeal: true    # Correct manual changes made in the cluster (drift detection)
    syncOptions:
      - CreateNamespace=true           # Automatically create the target namespace if it doesn't exist
      - PruneLast=true                 # Defer resource deletion until after new ones are applied (safer rollouts)
      - PrunePropagationPolicy=foreground # Gracefully delete dependent resources (recommended for safety)
      - ServerSideApply=true  