apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smartctl-exporter
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: prometheus-smartctl-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 0.16.0
    helm:
      valuesObject: 
        serviceMonitor:
          enabled: true
        # podAnnotations:
        #   prometheus.io/scrape: "true"
        prometheusRules:
          enabled: true
          extraLabels:
            release: kube-prometheus-stack
        hostNetwork: true
        
  syncPolicy:
    automated:
      prune: true       # Automatically delete resources no longer in Git
      selfHeal: true    # Correct manual changes made in the cluster (drift detection)
    syncOptions:
      - CreateNamespace=true           # Automatically create the target namespace if it doesn't exist
      - PruneLast=true                 # Defer resource deletion until after new ones are applied (safer rollouts)
      - PrunePropagationPolicy=foreground # Gracefully delete dependent resources (recommended for safety)
      - ServerSideApply=true  