kind: Deploy
type: helm
name: argocd
spec:
  namespace: argocd
  chart:
    name: argo-cd
    repo: https://argoproj.github.io/argo-helm
  values: 
    server:
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.0.220
---