kind: Deploy
type: helm
name: argocd
spec:
  namespace: argocd
  chart:
    name: argo-cd
    repo: https://argoproj.github.io/argo-helm
  values: 
    global:
      domain:
        admin-cluster-argocd.home
        
    configs:
      params:
        server.insecure: true
      cm:
        ui.title: Admin-Cluster ArgoCD
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
