apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: plex
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - plex.lester.network
    secretName: plex-tls
  rules:
  - host: plex.lester.network
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex
            port: 
              number: 32400