apiVersion: v1
kind: Service
metadata:
  name: ${var.app-name}
spec:
  type: ClusterIP
  selector:
    app: ${var.app-name}
  ports:
    - name: http
      port: 5030
      targetPort: 5030
    - name: https
      port: 5031
      targetPort: 5031
    - name: soulseek
      port: 50300
      targetPort: 50300