# ungrouped:
#   hosts:
#     gimli.home:
#   vars:
#     ansible_user: gimli
main:
  hosts:  
    gimli.home:
    helium.home:
    lithium.home:
  vars:
    ansible_user: atom
    
moonbase:
  hosts:
    moonbase.home:
  vars:
    ansible_user: root