$ANSIBLE_VAULT;1.1;AES256
39383666616632616562373530336632313133313034646563613339363436316437653035623031
3235633030663162613366393832313639383864333037390a346234333031303533323362366438
62326138323537643466393066663762393161353131633839343062373763363261653830366266
3531636434336333370a616536363864666438613266316139663866303137386161663036613264
64366630623266333166326331313062306131633639323633313663306530303934383961383430
62653637396235663465336333353566323961393535346432353464326331373630373934353338
62326562666265643430323064366366643538656235636363636164353932623234346437666363
36343635613930363466
