apiVersion: v1
kind: Secret
metadata:
  name: vpn-credentials
  namespace: qbittorrent
type: Opaque
stringData:
  username: ${var.vpn-username}
  password: ${var.vpn-password}
  private-key: ${var.nordvpn.private-key}