apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${var.app-name}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
#   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
  - host: ${var.app-name}.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${var.app-name}
            port: 
              number: 80