apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitwarden-ingress
  namespace: bitwarden
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - bitwarden.lester.network
      secretName: bitwarden-tls
  rules:
  - host: bitwarden.lester.network
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: bitwarden
            port: 
              number: 80