kind: Deploy
type: helm
description: Deploy ingress-nginx
name: ingress-nginx
spec:
  namespace: ingress-nginx
  chart: 
    name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.14.0
  values:
    controller:
      kind: DaemonSet
      ingressClassResource:
        default: true
      # metrics:
      #   enabled: true
      #   serviceMonitor:
      #     enabled: true
      service:
        loadBalancerIP: 192.168.0.200
      extraArgs: 
        enable-ssl-passthrough: "true"
        default-ssl-certificate: null